source_table: EMPLOYEES_SOURCE
target_table: EMPLOYEES_TARGET
pattern_check: 
  column_name: EMAIL
  pattern: "Can start with anything but should end with @DOMAIN.COM"
range_check:
  column_name: SAL
  min_value: 50000
  max_value: 200000
